---
- hosts: all
  remote_user: root

  tasks:
  - name: apt update
    apt:
      update_cache: yes
      upgrade: yes

  - name: install nginx
    apt:
      pkg: nginx

  - name: install git
    apt:
      pkg: git

  - name: install nodejs
    apt:
      pkg: nodejs

  - name: install npm
    apt:
      pkg: npm

  - name: install npm pm2
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: enter app directory
    shell: cd /home/ubuntu/app

  - name: installing ejs, mongoose and express
    shell: sudo npm install ejs mongoose express

  - name: populating posts page
    shell: node seeds/seed.js

  - name: removing default
    shell: sudo rm /etc/nginx/sites-enabled/default

  - name: replacing default
    shell: sudo ln -s /home/ubuntu/environment/app/default /etc/nginx/sites-enabled/default

  - name: stopping nginx
    shell: sudo systemctl stop nginx

  - name: starting nginx
    shell: sudo systemctl start nginx

  - name: nginx
    shell: sudo nginx -t
